site_name: COMP423 Course Notes
nav:
  - Home: index.md
  - Go Dev Container Tutorial: tutorials/go-setup.md
theme:
  palette:
    scheme: slate
    primary: amber
  features:
    - content.code.copy
    - content.code.annotate
  name: material
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences